GET http://localhost:8000/users

###

GET http://localhost:8000/users/Juan

###

POST http://localhost:8000/users
Content-Type: application/json

{
    "_id": 4,
    "username": "pepet",
    "pass": "1234"
}

###

POST http://localhost:8000/users
Content-Type: application/json

###

PUT http://localhost:8000/users/Aaron2
Content-Type: application/json

{
    "_id": 4,
    "username": "juan",
    "pass": "1234"
}
###

DELETE http://localhost:8000/users/4


